### ISSUE TITLE
Barcodes don't scan

### ISSUE THREAD

**Issue by AndrewBWS** [bywatersolutions/koha-plugin-label-maker#2]
[barcodes.pdf](https://github.com/bywatersolutions/koha-plugin-label-maker/files/3763417/barcodes.pdf)

Barcodes generated in the plugin seem to lack the start and end characters required for scanning. Printing through the native label printer generates barcodes correctly. Only tested this with Code 39 barcodes.

**Comment by kylemhall** [comment]
The plugin relies on the barcode service built into Koha for barcode image generation.

The solutions are to either
A) Consider it standard practice to wrap the barcode with asterisks any time the barcode svc script is used, or
B) File a community bug to add the automatic wrapping of barcodes with asterisks for code39 barcodes.
