### ISSUE TITLE
Sintax for Printer Profile

### ISSUE THREAD

**Issue by nikolaslibert** [bywatersolutions/koha-plugin-label-maker#9]
I couldn't find anywhere an example for the printer profile. Maybe you could write down a list of allowed keywords in the edit page.

**Comment by kylemhall** [comment]
Printer profiles are just printer-specific CSS you would use to push around your content to alignment purposes. [Here](https://github.com/bywatersolutions/koha-plugin-label-maker/blob/8a49993ea417b853b3fa82393001453e92dd6f5f/Koha/Plugin/Com/ByWaterSolutions/LabelMaker/print_labels.tt#L27) you can see that whatever is set for the profile is just wrapped in style tags before embedding.
